version: "3.8"

services:
  frontend:
    image: sanelevilakazi/mern-frontend
    depends_on:
      - server
    ports:
      - '3001:3001'
    environment:
      - REACT_APP_API_URL=http://server:3000
    container_name: frontendapp_c
    restart: always
    networks:
      - app-network

  server:
    image: sanelevilakazi/mern-backend-api
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://root:db:27017//data/db
    container_name: backendapp_c
    restart: always
    networks:
      - app-network

  db:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/StudentMarks
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge