# The version of the docker-compose.
version: "3.8"

# Telling docker-compose to build the client and server images and run them in containers.
services:
  frontend:
    image: sanelevilakazi/mern-frontend
    depends_on:
      - server
    ports:
      - '3001:3001'
    environment:
      - REACT_APP_API_URL=http://localhost:3000

    container_name: frontendapp_c
    restart: always
    networks:
      - app-network

  server:
    image: sanelevilakazi/mern-backend-api
    depends_on:
      - mongo
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://root:example@db:27017/StudentMarks
    container_name: backendapp_c
    restart: always
    networks:
      - app-network
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge