# The version of the docker-compose.
version: "3.8"

services:
  client:
    build: ./frontend
    container_name: frontendapp_c
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    depends_on:
      - server

  server:
    build: ./backend
    container_name: backendapp_c
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    depends_on:
      db:
        condition: service_healthy  # ✅ Waits for MongoDB to be ready

  db:
    image: mongo
    container_name: mongodb_c
    restart: always  # ✅ Ensures MongoDB restarts if it crashes
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:  # ✅ Ensures MongoDB is ready before backend starts
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet mongodb://root:example@db:27017/admin
      interval: 10s
      retries: 5
      start_period: 20s

# Define volumes
volumes:
  mongodb_data:
